In [1]:
import gym
import numpy as np
import time
from scipy.stats import pearsonr
from IPython.display import clear_output

env=gym.make("FrozenLake-v0")
action_space_size=env.action_space.n
state_space_size=env.observation_space.n
q_table=np.zeros((state_space_size,action_space_size))
#tried to implement the following research paper:-
#Reinforcement Learning in Video Games Using NearestNeighborInterpolation and MetricLearning
#Matthew S. Emigh, Evan G. Kriminger, Austin J.Brockmeier, Member, IEEE, José C. Príncipe, Fellow, IEEE, and Panos M. Pardalos

'''

sigma=10
random.seed(30)
Y=q_table()
X=np.random.random(low=0,high=state_space_size-1,size=(state_space_size,action_space_size))
w = (2*np.random.rand(state_space_size,action_space_size) - 1)/2

for action in action_space_size:
    for epochs in range(100):
        corr_X_Y=[]
    
        for j in range(state_space_size):
        
            kX=np.exp(-w[:,action].T.dot(np.square(X[j][action]-X[:,action])))
            kY=np.exp(-(np.square(Y[i][j]-Y[:,j])/(2*sigma*sigma)))
            #H=np.identity(state_space_size)-(1/state_space_size)*(np.ones((16,1)).dot(np.ones(16,1).T))
        
            #X_=np.dot(H.dot(X),H)
            #Y_=np.dot(H.dot(Y),H)
            for i in range(state_space_size):
                corr_X_Y.append(pearsonr(kX[i],kY[i]))
        
        F=np.log(corr_X_Y)
           
        
            
'''
episodes=10000
max_steps_per_episode=200
exploration_rate=1
min_exploration_rate=0.001
max_exploration_rate=1
exploration_decay=0.001

learning_rate=0.1
discount_rate=0.99
rewards_all_episodes=[]
for i in range(episodes):
    state=env.reset()
    reward_per_episode=0
    done=False
    for steps in range(max_steps_per_episode):
        threshold=np.random.uniform(0,1)
        if(exploration_rate>threshold):
            action=env.action_space.sample()
        else:
            action=np.argmax(q_table[state,:])

        new_state,reward,done,info=env.step(action)
        reward_per_episode+=reward
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        state=new_state
        if done:
            break
        
        #def q_table():
            #if episodes==2000:
                #return q_table
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay*i)
    rewards_all_episodes.append(reward_per_episode)
reward_per_1000_epi=np.split(np.array(rewards_all_episodes),episodes/1000)

#after training
#lets play
Time=[]
for episode in range(5):
    print("******episode ",episode+1,"*******")
    time.sleep(3)
    start=time.time()
    state=env.reset()
    done=False
    for steps in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action=np.argmax(q_table[state,:])
        new_state,reward,done,info=env.step(action)
        state=new_state
        if done:
            if reward==1:
                print("Reached the goal!!!")
                stop=time.time()
                print('Time taken to reach the goal:',stop-start, 'seconds')
                time.sleep(3)
            else:
                print("You hit a hole")
                stop=time.time()
                print('Hits the hole in ',stop-start, 'seconds')
                time.sleep(3)

            clear_output(wait=True)
            break;
#Accuracy
count=1000
for i in reward_per_1000_epi:
    print(count," episodes:",np.mean(i))
    count+=1000
print('Q-table\n',q_table)
env.close()

1000  episodes: 0.047
2000  episodes: 0.224
3000  episodes: 0.412
4000  episodes: 0.549
5000  episodes: 0.662
6000  episodes: 0.712
7000  episodes: 0.702
8000  episodes: 0.734
9000  episodes: 0.699
10000  episodes: 0.72
Q-table
 [[0.50565059 0.4694427  0.45826787 0.46488802]
 [0.3141382  0.25544101 0.32516204 0.50743609]
 [0.37211395 0.37638461 0.37290648 0.46266395]
 [0.36366193 0.29754882 0.31866926 0.44205291]
 [0.52027395 0.40642312 0.30261254 0.46692857]
 [0.         0.         0.         0.        ]
 [0.16100626 0.11625868 0.19601687 0.16038885]
 [0.         0.         0.         0.        ]
 [0.35131027 0.40472803 0.2825338  0.54097069]
 [0.46173941 0.60288191 0.43377237 0.4516411 ]
 [0.57438378 0.30346852 0.36156682 0.33213606]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.41506527 0.44012419 0.76212413 0.38904119]
 [0.69105309 0.86056568 0.72598444 0.71275737]
 [0.         0.         0.         0.        ]]
